#!/bin/bash

# Author: Anne C. van Rossum
# License: GNU LGPLv3 
# Date: Jun. 17, 2012

PROGRAM="aimrun"

VERSION="0.2"

#######################################################################################################################
# Default configuration
#######################################################################################################################

AIM_CONFIG_PATH=/etc/aim
AIM_CONFIG_FILE=/etc/aim/config.sh

source $AIM_CONFIG_FILE
source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY

#######################################################################################################################
# User configuration
#######################################################################################################################

if [ -e ${RUR_CONFIG_FILE_BACKENDS} ]; then
	source $RUR_CONFIG_FILE_BACKENDS
fi

#######################################################################################################################
# Argument checks
#######################################################################################################################

if [[ "$1" == "" ]]
then
	msg_error "No args supplied! Run $0 -h for more info"
	exit 1
fi

if [[ "$1" == "-h" ]]
then
	echo $PROGRAM $VERSION \- Usage
	echo 
	echo $PROGRAM \"ModuleName\" \"ModuleId\"
	echo
	exit 0 
fi 

if [[ $# -ne 2 ]]
then
	msg_error "We need two parameters. Run $0 -h for more info, currently you used $# parameters"
	exit 1
fi

#######################################################################################################################
# Start
#######################################################################################################################

MODULE_NAME=${1%/}
ModuleId=${2%/}

BUILD_FOLDER=builds/standard

msg_info "Search in ${AIM_REGISTRY}"
SUCCESS=false
MODULE_FULLNAME=
while read LINE; do
	MODULE_I=`echo "$LINE" | cut -d'=' -f 1`
	M_I_STRIPPED=${MODULE_I//[[:space:]]}
#	echo $M_I_STRIPPED
	if [[ "$M_I_STRIPPED" == "$1" ]]; then
#		echo "$MODULE_NAME found. Run it"
		MODULE_FULLNAME=`echo "$LINE" | cut -d'=' -f 2`
		SUCCESS=true
		break
	fi
done < "${AIM_REGISTRY}"

# Shift so, $@ becomes second argument (id) and further on
shift

if [[ $SUCCESS == true ]]; then
	msg_info "Run: \"$MODULE_FULLNAME/$BUILD_FOLDER/$MODULE_NAME $@\" (includes all command-line arguments)"
	msg_info "The output of the module itself is in between two horizontal lines:"
	echo "--------------------------------------------------------------------------------"
	$MODULE_FULLNAME/$BUILD_FOLDER/$MODULE_NAME "$@"
	echo "--------------------------------------------------------------------------------"
	msg_info "Exit of \"$MODULE_NAME\" (error code is not returned)"
	exit 0
else
	msg_warning "No such module found ($MODULE_NAME). Did you use aimregister to register this module on this machine?"
	exit 1
fi


