#!/bin/bash

# Author: Anne C. van Rossum
# License: GNU LGPLv3 
# Date: Jun. 17, 2012

PROGRAM="aimget"

VERSION="0.2"

#######################################################################################################################
# Default configuration
#######################################################################################################################

AIM_CONFIG_PATH=/etc/aim
AIM_CONFIG_FILE=/etc/aim/config.sh

source $AIM_CONFIG_FILE
source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY

#######################################################################################################################
# User configuration
#######################################################################################################################

if [ -e ${RUR_CONFIG_FILE_BACKENDS} ]; then
	source $RUR_CONFIG_FILE_BACKENDS
fi

#######################################################################################################################
# Argument checks
#######################################################################################################################

if [[ "$1" == "" ]]
then
	msg_error "No args supplied! Run $0 -h for more info"
	exit 1
fi

if [[ "$1" == "-h" ]]
then
	echo "$PROGRAM $VERSION - Usage"
	echo 
	echo "$PROGRAM \"repository name\" \"repository url\""
	echo "  for example: $PROGRAM computervision https://github.com/mrquincle/aim_modules"
	echo "  the repository name will be used to be able to maintain multiple repositories"
	echo
	echo "Set AIM_WORKSPACE as environmental variable before you use this tool"
	echo "  for example: export AIM_WORKSPACE=$HOME/aim_workspace"
	echo
	echo "Dependency: git"
	exit 0 
fi 

if [[ $# -ne 2 ]]
then
	msg_error "We need two parameters. Run $0 -h for more info, currently you used $# parameters"
	exit 1
fi

#######################################################################################################################
# Start
#######################################################################################################################

REPOS_NAME=$1
REPOS_URL=$2

: ${AIM_WORKSPACE:? "Set AIM_WORKSPACE as environmental variable before you use this tool"}

[ ! -d $AIM_WORKSPACE ] && msg_info "Workspace path \"$AIM_WORKSPACE\" not found" && exit 0
	
msg_info "We will use $AIM_WORKSPACE for a workspace"

cd $AIM_WORKSPACE

if [[ $REPOS_URL =~ .*github.* ]]; then
	msg_info "This is a github repository"
	msg_info "git clone $REPOS_URL $REPOS_NAME"
	[ -d $REPOS_NAME ] && msg_info "Directory \"$REPOS_NAME\" already exists" && exit 0
	git clone $REPOS_URL $REPOS_NAME
fi

