#!/bin/bash

PROGRAM="aimports"

VERSION="0.1"

#######################################################################################################################
# Default configuration
#######################################################################################################################

AIM_CONFIG_PATH=/etc/aim
AIM_CONFIG_FILE=/etc/aim/config.sh

include () {
	test -f "$1" && source "$1"
}

#echo -e "[#] $(date +"%x %R") - Info: Source config files"
source $AIM_CONFIG_FILE
source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY

msg_init $PROGRAM

#######################################################################################################################
# Argument checks
#######################################################################################################################

if [[ $AIM_VERSION != $VERSION ]]; then
	msg_error "${PROGRAM} is version ${VERSION}, while it should be version ${AIM_VERSION}."
	exit 0
fi

if [[ "$1" == "-h" ]]
then
	echo $PROGRAM $VERSION \- Usage
	echo 
	echo $PROGRAM 
	echo
	exit 0 
elif [ $# -ne 1 ]
then
	echo "One and only one argument should be supplied!"
	exit 1
fi 

AIM_REGISTRY=$1.ports
# echo ${AIM_REGISTRY}

# echo "Search in ${RUR_HOME}/${AIM_REGISTRY}"

index=0
while read LINE; 
do
	port=$LINE
	# port=`echo "$LINE" | cut -d' ' -f 1`
	#if port -e "in"
	#elif port -e "out"
	#fi
	Registered_port[$index]=$port
	index=$(($index + 1))
#	echo $LINE
#	echo $M_I_STRIPPED
done < "${RUR_REGISTRY_PATH}/${AIM_REGISTRY}"

#echo "success!!"

tLen=${#Registered_port[@]}
# use for loop read all nameservers
for (( i=0; i<${tLen}; i++ ));
do
  echo ${Registered_port[$i]}
done




