#!/bin/bash

PROGRAM="aimstop"

VERSION="0.3"

#######################################################################################################################
# Default configuration
#######################################################################################################################

AIM_CONFIG_PATH=/etc/aim
AIM_CONFIG_FILE=/etc/aim/config.sh

source $AIM_CONFIG_FILE
source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY
source $AIM_CONFIG_REGISTRY_CHECK

msg_init $PROGRAM

#######################################################################################################################
# User configuration
#######################################################################################################################

if [ -e ${RUR_CONFIG_FILE_BACKENDS} ]; then
	source $RUR_CONFIG_FILE_BACKENDS
fi

#######################################################################################################################
# Argument checks
#######################################################################################################################

if [[ $AIM_VERSION != $VERSION ]]; then
	msg_error "${PROGRAM} is version ${VERSION}, while it should be version ${AIM_VERSION}."
	exit 0
fi

if [[ "$1" == "-h" ]]
then
	echo "$PROGRAM $VERSION - Usage"
	echo 
	echo "$PROGRAM \"middleware\" \"module name\" \"module id\""
	echo
	exit 0 
fi 

if [[ $# -ne 3 ]]
then
	msg_error "We need three parameters. Run $0 -h for more info, currently you used $# parameters"
	exit 1
fi

MIDDLEWARE=${1%}
MODULE_NAME=${2%/}
ModuleId=${3%/}

# read the registry and find the location of the module
msg_info "Search in ${AIM_REGISTRY}"
SUCCESS=false
reg_check $MODULE_NAME MODULEFULLNAME
if [[ "$MODULEFULLNAME" != "" ]]; then
	SUCCESS=true
fi

# After having found the location in the registry, remove the reference to git/repo from the modulename to properly start the module
MODULE_NAME=$(basename $MODULE_NAME)

index=0
Registered_port={}
while read LINE; do
        port=$(echo "$LINE" | cut -d' ' -f 2)
	Registered_port[$index]=$port
	index=$(($index + 1))
        #echo $port
done < "${RUR_REGISTRY_PATH}/$MODULE_NAME.ports"


if [[ ! $SUCCESS == true ]]; then
	msg_error "No such module found ($MODULE_NAME)"
	exit 1
fi	

if [[ $MIDDLEWARE == "yarp" ]]; then
	# for port1 in $Registered_port
	for (( i=0; i< $index; i++ ))
	do
		echo ${Registered_port[$i]}
		yarp terminate /${MODULE_NAME,,}$ModuleId/${Registered_port[$i]}
	done
	yarp clean
	exit 0
fi

msg_info "Stop $MODULE_NAME $ModuleId in a rigorous manner"
pkill -9 $MODULE_NAME
exit 0
