#!/bin/bash

PROGRAM="aimlist"

VERSION="0.3"

#######################################################################################################################
# Default configuration
#######################################################################################################################

AIM_CONFIG_PATH=/etc/aim
AIM_CONFIG_FILE=/etc/aim/config.sh

source $AIM_CONFIG_FILE
source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY

msg_init $PROGRAM


####################################################################################################
# User configuration
####################################################################################################

if [ -e ${RUR_CONFIG_FILE_BACKENDS} ]; then
	source $RUR_CONFIG_FILE_BACKENDS
fi

####################################################################################################
# Checks
####################################################################################################

if [[ $AIM_VERSION != $VERSION ]]; then
	msg_error "${PROGRAM} is version ${VERSION}, while it should be version ${AIM_VERSION}."
	exit 0
fi

if [[ "$1" == "-h" ]] ; then
	echo $PROGRAM $VERSION \- Usage
	echo 
	echo "$PROGRAM"
	exit 0
fi 

index=0
while read LINE; 
do
	MODULE_I=`echo "$LINE" | cut -d'=' -f 1 | sed 's/ *$//g'`
	MODULE_I=${MODULE_I%/}
	Registered_Module[$index]=$MODULE_I
	index=$(($index + 1))
done < "${AIM_REGISTRY}"

tLen=${#Registered_Module[@]}

# use for loop read all nameservers
echo "{"
echo "  \"modules\": ["
for (( i=0; i<${tLen}; i++ ));
do
	echo "    {"
	echo "      \"name\": \"${Registered_Module[$i]}\""
	if [ $i -eq $((${tLen} - 1)) ]; then
		echo "    }"
	else
		echo "    },"
	fi
done
echo "  ] "
echo "}"



