#!/bin/bash

PROGRAM="aimlist"

VERSION="0.3"

#######################################################################################################################
# Default configuration
#######################################################################################################################

AIM_CONFIG_PATH=/etc/aim
AIM_CONFIG_FILE=/etc/aim/config.sh

source $AIM_CONFIG_FILE
source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY

msg_init $PROGRAM


####################################################################################################
# User configuration
####################################################################################################

if [ -e ${RUR_CONFIG_FILE_BACKENDS} ]; then
	source $RUR_CONFIG_FILE_BACKENDS
fi

####################################################################################################
# Checks
####################################################################################################

if [[ $AIM_VERSION != $VERSION ]]; then
	msg_error "${PROGRAM} is version ${VERSION}, while it should be version ${AIM_VERSION}."
	exit 0
fi

if [[ "$1" == "-h" ]]
then
	echo $PROGRAM $VERSION \- Usage
	echo 
	echo "$PROGRAM mode"
	echo "  mode=0 means to list all CS* modules"
	echo "  mode=1 means to list all non-Login modules"
	echo
	exit 0 
elif [ $# -ne 1 ]
then
	msg_error "One and only one argument is expected!"
	exit 1
fi 


MODULE_FULLNAME=
FirstTwo=
index=0
while read LINE; 
do
	MODULE_I=`echo "$LINE" | cut -d'=' -f 1 | sed 's/ *$//g'`
	MODULE_I=${MODULE_I%/}
	FirstTwo=`echo "$MODULE_I" | cut -c1-2`
	MiddleFive=`echo "$MODULE_I" | cut -c3-7`
	if [ "$1" -eq 0 ]; then
		if [[ "$FirstTwo" != "CS" ]]; then 
			Registered_Module[$index]=$MODULE_I
			# echo $index
			index=$(($index + 1))
		fi
	elif [ "$1" -eq 1 ]; then
		if [[ "$MiddleFive" != "Login" ]]; then
			Registered_Module[$index]=$MODULE_I
			index=$(($index + 1))
		fi
	else
		msg_error "Only two modes (0 and 1) are expected, please check!"
		exit 1
	fi

#	echo $LINE
#	echo $M_I_STRIPPED
done < "${AIM_REGISTRY}"
#echo $index
#echo "success!!"

tLen=${#Registered_Module[@]}

# use for loop read all nameservers
echo "{"
echo "  \"modules\": ["
for (( i=0; i<${tLen}; i++ ));
do
	echo "    {"
	echo "      \"name\": \"${Registered_Module[$i]}\""
	if [ $i -eq $((${tLen} - 1)) ]; then
		echo "    }"
	else
		echo "    },"
	fi
done
echo "  ] "
echo "}"



